apiVersion: v1
kind: Service
metadata:
  name: devops-portfolio-svc
  namespace: portfolio
spec:
  type: LoadBalancer
  selector:
    app: devops-portfolio
  ports:
    - port: 80
      targetPort: 8080
